### ISSUE TITLE
Async problem when preprocess is involved.

### ISSUE THREAD

**Issue by farhan2106** [rspieker/jest-transform-svelte#11]
Somehow, `svelte.preprocess` hangs and not able to output the preprocess code. I am not sure if it is a problem with `svelte.preprocess` or `deasync` or is it my config? You can checkout of my repo. 

https://github.com/farhan2106/sveltangular

![Screenshot from 2019-11-04 11-53-01](https://user-images.githubusercontent.com/897173/68098777-b34d2500-fef9-11e9-8b8d-3d4377d7ee93.png)
![Screenshot from 2019-11-04 11-54-14](https://user-images.githubusercontent.com/897173/68098813-da0b5b80-fef9-11e9-9c1f-7d15c83f4ef1.png)

The component being tested is very simple
```
<script lang="typescript">
  const name: string = 'Sample';
</script>

<style>
</style>

<template>
  <p>`{ name }` component loaded!.</p>
</template>
```
The test is also straight forward.
```
import Sample from './Sample.svelte';

test('component should load', () => {
  new Sample({
    target: document.body
  })
  expect(document.body.innerHTML).toBe('<p>`Sample` component loaded!.</p>');
});
```

Here is my jest config.
```
module.exports = {
  clearMocks: true,
  collectCoverage: true,
  coverageDirectory: "coverage",
  moduleFileExtensions: [
    "js",
    "json",
    "jsx",
    "ts",
    "tsx",
    "node",
    "svelte"
  ],
  "transform": {
    "\\.js$": "babel-jest",
    '^.+\\.tsx?$': 'ts-jest',
    '^.+\\.svelte$': ['jest-transform-svelte', {
      preprocess: autoPreprocess({
        typescript: {
          transpileOnly: true
        }
      })
    }]
  }
};

```

**Comment by rspieker** [comment]
This should be resolved now (thanks to #15), released as 2.1.1
