### ISSUE TITLE
Async issue with `preprocess` option still exists

### ISSUE THREAD

**Issue by ryexley** [rspieker/jest-transform-svelte#17]
We are also experiencing the issue with node v12.x and tests hanging forever when using the `preprocess` option. We've seen the [existing](https://github.com/rspieker/jest-transform-svelte/issues/11) [issues](https://github.com/rspieker/jest-transform-svelte/issues/12) reporting this problem and noticed that they were reported as having been fixed, but unfortunately we still see the same problem, even using the patched version.

This is our what we currently have installed, and we're still seeing the issue:

```
npm ls deasync
sapper-test-app@0.0.1 /Users/me/projects/sapper-test-app
└─┬ jest-transform-svelte@2.1.1
  └── deasync@0.1.19
```

I would assume that since you state that it's fixed that you've been able to get this working at some point. I am currently running node v12.14.1 with the above dependency versions and I'm still seeing the hanging issue.

Everything works fine when we use node v10.x, but when we upgrade to 12 we see the issue. We'd like to be able to upgrade to node 12, because we have need of using svelte-i18n as well, which requires at least node v11.

Is there some other factor other than the above dependency versions that might be contributing to this?

**Comment by ryexley** [comment]
So, I did some spelunking and was able to figure out what our issue was. I had been following the example in the README for configuring preprocessing, and had our jest config setup like so:

```js
const sveltePreprocess = require('svelte-preprocess')
const { scss } = sveltePreprocess

transform: {
	...
  '^.+\\.svelte$': ['jest-transform-svelte', { preprocess: sveltePreprocess([scss()]) }]
}
```

When I dug in to the source for the transform and put some console.logs in there, I was noticing that it was getting `{}` for the `preprocess` option. Not sure why it was getting an empty object, but that made it clear that something was wrong. It's still not clear to me why I had to do this, but I was able to get it working by changing our config to this:

```js
const sveltePreprocess = require('svelte-preprocess')
const { scss } = sveltePreprocess

transform: {
	...
  '^.+\\.svelte$': ['jest-transform-svelte', { preprocess: () => sveltePreprocess([scss()]) }]
}
```

Unless I'm doing something wrong, this was the only way it would work. If there is another correct way, someone please inform me. If this is correct, it would be helpful for others to get the README updated to reflect this.

**Comment by dhrep** [comment]
This is still an issue, using the above jest config.
