### ISSUE TITLE
need test example that fires an event

### ISSUE THREAD

**Issue by mvolkmann** [rspieker/jest-transform-svelte#3]
Sorry to be a pest. The current test examples just show testing that a component renders properly, but not any user interaction with a component. Could you add an example test where you fire an event that results in a DOM update that you test for? For example, it could be something like clicking a button that adds something to a list. I've been unable to get something like that to work.

**Comment by rspieker** [comment]
I do appreciate the requests for more documentation, and I did see some value in your request. 
Ultimately this is a module trying to bring Svelte and Jest together, it's not intended to be an exhaustive resource on the finer details on either system.
