### ISSUE TITLE
need a way to pass in rollup options / plugins

### ISSUE THREAD

**Issue by elialbert** [rspieker/jest-transform-svelte#4]
I had to copy this into my app in order to add commonjs to the list of rollup plugins, so that I could have something like 
`commonjs({
      namedExports: {
        'moment': ['isValidElementType']
      }
    })`

otherwise moment wasn't importing properly.
https://stackoverflow.com/a/41052019
Just a thought.

**Comment by rspieker** [comment]
Thank you for your request!
From what I collected on possible options so far (I'm not a frequent user of Jest) there are two ways to configure transformers, one being using json (of which there's a sample in the README), and there's the option to use a plain javascript configuration, I would assume the latter would be the prefered option.

I'll look into that approach and see how it would work, right now I'm mostly worried about the ordering of plugins, which always seems a little delicate and could possible interfere with the simplicity of this transformer.

**Comment by elialbert** [comment]
cool thanks for the thoughtful response. 
hadn't thought about ordering - but if it's all up to the user, seems like they should be able to figure out the ordering they need?
As someone installing this in a package.json to run on .svelte files, ideal would be some way to specify it right there. That said, I think having a magic string rollup-config.js or jest-transform-rollup-config.js or whatever might be cleaner and easier. Honestly not sure what best practices are for this.

**Comment by rspieker** [comment]
Ah, didn't consider putting the configuration in the package.json, that seems to work pretty well for jest itself, so I could probably do something along the lines of:

```
"jest-transform-svelte": [
  {
    "plugin": "rollup-plugin-commonjs", 
    "options": { "namedExports": { "moment": [ "isValidElementType"] } }
  },
  "rollup-plugin-node-resolve",
  "rollup-plugin-svelte"
]
```
This is on the assumption (I know...) that your commonjs use case would need to be execute before svelte, that lead me into considering the order.

I'm not sure if something like that would be frowned upon, as I'd have to include the plugins dynamically (and I'd have to trust them to be installed), but it would open up for having both the order and options.
I don't think I've seen something similar in a package.json before, but having something like this in place could then also open up for a separate config file

**Comment by elialbert** [comment]
cool!
for reference, my hacky patch just looked like:
```
rollup
    .rollup({ input, plugins: [svelte(), resolve(), commonjs({
      namedExports: {
        'moment': ['isValidElementType']
      }
...etc

```
so in my case commonjs did not need to execute before svelte. 
I think trusting the user to install plugins is fine; I've seen all sorts of things like that in the crazy wild west that is javascript today.
